
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '2FF9760A20F7B4C9FF6986ABDA200E3C'
    
_lr_action_items = {'DO':([6,],[7,]),'RETURN':([8,41,],[10,10,]),'DEFAULT':([8,41,],[28,28,]),'IN':([45,],[63,]),'WITH':([62,],[74,]),'APPEND':([8,41,71,78,],[19,19,83,89,]),'SET':([8,41,],[16,16,]),']':([36,],[52,]),'CREATE':([8,41,],[18,18,]),',':([32,35,67,79,],[-12,-10,-11,90,]),'.':([35,],[51,]),'TO':([19,],[43,]),'CHANGE':([8,41,],[11,11,]),'=':([40,46,48,54,],[59,64,65,69,]),'READ':([71,78,],[81,87,]),'$end':([2,47,],[0,-1,]),'STRING':([5,10,55,59,61,64,69,74,85,],[6,32,70,32,73,32,32,32,32,]),'REPLACEWITH':([75,],[85,]),'DELEGATION':([16,31,],[39,49,]),'AS':([0,],[1,]),'FOREACH':([8,41,],[24,24,]),'ARROW':([80,81,82,83,86,87,88,89,],[91,92,93,94,96,97,98,99,]),'ENTER':([7,9,12,13,14,15,17,20,21,22,26,29,30,32,33,34,35,52,67,68,70,72,73,76,77,84,95,101,102,103,104,105,106,107,108,],[8,-15,-13,-19,-20,-16,41,44,-18,-17,-21,-37,-14,-12,50,-5,-10,-6,-11,-7,-23,-24,-22,-26,-36,-25,-27,-30,-29,-31,-28,-34,-33,-35,-32,]),'[':([10,59,64,74,85,],[36,36,36,36,36,]),'PASSWORD':([4,11,],[5,38,]),'LOCAL':([8,41,],[25,25,]),'ID':([3,10,16,24,25,37,38,39,42,43,49,51,56,57,58,59,63,64,65,66,69,74,85,90,91,92,93,94,96,97,98,99,],[4,35,40,45,46,54,55,58,61,62,58,67,-39,71,-40,35,75,35,77,78,35,35,35,54,101,102,103,104,105,106,107,108,]),'WRITE':([71,78,],[80,86,]),'ALL':([39,49,],[56,56,]),'TERMINATE':([23,27,44,50,60,],[-3,47,-2,-38,-4,]),'EXIT':([8,41,],[29,29,]),'DELEGATE':([71,78,],[82,88,]),'{':([10,59,64,74,85,],[37,37,37,37,37,]),'DELETE':([8,41,],[31,31,]),'}':([32,35,53,67,79,100,],[-12,-10,68,-11,-8,-9,]),'DELEGATOR':([28,],[48,]),'PRINCIPAL':([1,18,],[3,42,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'default_delegator':([8,41,],[26,26,]),'fieldvals':([37,90,],[53,100,]),'set':([8,41,],[9,9,]),'return':([8,41,],[23,23,]),'tgt':([39,49,],[57,66,]),'prim_cmd':([8,41,],[17,17,]),'cmd':([8,41,],[27,60,]),'value':([10,59,64,69,74,85,],[34,34,34,79,34,34,]),'create_principal':([8,41,],[12,12,]),'expr':([10,59,64,74,85,],[33,72,76,84,95,]),'set_delegation':([8,41,],[13,13,]),'exit':([8,41,],[20,20,]),'foreach':([8,41,],[21,21,]),'change_password':([8,41,],[30,30,]),'prog':([0,],[2,]),'delete_delegation':([8,41,],[14,14,]),'local':([8,41,],[22,22,]),'append':([8,41,],[15,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> prog","S'",1,None,None,None),
  ('prog -> AS PRINCIPAL ID PASSWORD STRING DO ENTER cmd TERMINATE','prog',9,'p_prog','server',170),
  ('cmd -> exit ENTER','cmd',2,'p_cmd','server',175),
  ('cmd -> return','cmd',1,'p_cmd','server',176),
  ('cmd -> prim_cmd ENTER cmd','cmd',3,'p_cmd','server',177),
  ('expr -> value','expr',1,'p_expr','server',191),
  ('expr -> [ ]','expr',2,'p_expr','server',192),
  ('expr -> { fieldvals }','expr',3,'p_expr','server',193),
  ('fieldvals -> ID = value','fieldvals',3,'p_fieldvals','server',205),
  ('fieldvals -> ID = value , fieldvals','fieldvals',5,'p_fieldvals','server',206),
  ('value -> ID','value',1,'p_value','server',216),
  ('value -> ID . ID','value',3,'p_value','server',217),
  ('value -> STRING','value',1,'p_value','server',218),
  ('prim_cmd -> create_principal','prim_cmd',1,'p_prim_cmd','server',226),
  ('prim_cmd -> change_password','prim_cmd',1,'p_prim_cmd','server',227),
  ('prim_cmd -> set','prim_cmd',1,'p_prim_cmd','server',228),
  ('prim_cmd -> append','prim_cmd',1,'p_prim_cmd','server',229),
  ('prim_cmd -> local','prim_cmd',1,'p_prim_cmd','server',230),
  ('prim_cmd -> foreach','prim_cmd',1,'p_prim_cmd','server',231),
  ('prim_cmd -> set_delegation','prim_cmd',1,'p_prim_cmd','server',232),
  ('prim_cmd -> delete_delegation','prim_cmd',1,'p_prim_cmd','server',233),
  ('prim_cmd -> default_delegator','prim_cmd',1,'p_prim_cmd','server',234),
  ('create_principal -> CREATE PRINCIPAL ID STRING','create_principal',4,'p_create_principal','server',240),
  ('change_password -> CHANGE PASSWORD ID STRING','change_password',4,'p_change_password','server',245),
  ('set -> SET ID = expr','set',4,'p_set','server',250),
  ('append -> APPEND TO ID WITH expr','append',5,'p_append','server',255),
  ('local -> LOCAL ID = expr','local',4,'p_local','server',260),
  ('foreach -> FOREACH ID IN ID REPLACEWITH expr','foreach',6,'p_foreach','server',265),
  ('set_delegation -> SET DELEGATION tgt ID APPEND ARROW ID','set_delegation',7,'p_set_delegation','server',270),
  ('set_delegation -> SET DELEGATION tgt ID READ ARROW ID','set_delegation',7,'p_set_delegation','server',271),
  ('set_delegation -> SET DELEGATION tgt ID WRITE ARROW ID','set_delegation',7,'p_set_delegation','server',272),
  ('set_delegation -> SET DELEGATION tgt ID DELEGATE ARROW ID','set_delegation',7,'p_set_delegation','server',273),
  ('delete_delegation -> DELETE DELEGATION tgt ID APPEND ARROW ID','delete_delegation',7,'p_delete_delegation','server',278),
  ('delete_delegation -> DELETE DELEGATION tgt ID READ ARROW ID','delete_delegation',7,'p_delete_delegation','server',279),
  ('delete_delegation -> DELETE DELEGATION tgt ID WRITE ARROW ID','delete_delegation',7,'p_delete_delegation','server',280),
  ('delete_delegation -> DELETE DELEGATION tgt ID DELEGATE ARROW ID','delete_delegation',7,'p_delete_delegation','server',281),
  ('default_delegator -> DEFAULT DELEGATOR = ID','default_delegator',4,'p_default_delegator','server',286),
  ('exit -> EXIT','exit',1,'p_exit','server',291),
  ('return -> RETURN expr ENTER','return',3,'p_return','server',296),
  ('tgt -> ALL','tgt',1,'p_tgt','server',301),
  ('tgt -> ID','tgt',1,'p_tgt','server',302),
]
